// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: preview.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PreviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreviewRequest) Reset() {
	*x = PreviewRequest{}
	mi := &file_preview_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewRequest) ProtoMessage() {}

func (x *PreviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_preview_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewRequest.ProtoReflect.Descriptor instead.
func (*PreviewRequest) Descriptor() ([]byte, []int) {
	return file_preview_proto_rawDescGZIP(), []int{0}
}

func (x *PreviewRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type PreviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreviewResponse) Reset() {
	*x = PreviewResponse{}
	mi := &file_preview_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewResponse) ProtoMessage() {}

func (x *PreviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_preview_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewResponse.ProtoReflect.Descriptor instead.
func (*PreviewResponse) Descriptor() ([]byte, []int) {
	return file_preview_proto_rawDescGZIP(), []int{1}
}

func (x *PreviewResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PreviewResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_preview_proto protoreflect.FileDescriptor

const file_preview_proto_rawDesc = "" +
	"\n" +
	"\rpreview.proto\x12\apreview\"\"\n" +
	"\x0ePreviewRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"I\n" +
	"\x0fPreviewResponse\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription2Q\n" +
	"\x0ePreviewService\x12?\n" +
	"\n" +
	"GetPreview\x12\x17.preview.PreviewRequest\x1a\x18.preview.PreviewResponseB\x17Z\x15preview-service/protob\x06proto3"

var (
	file_preview_proto_rawDescOnce sync.Once
	file_preview_proto_rawDescData []byte
)

func file_preview_proto_rawDescGZIP() []byte {
	file_preview_proto_rawDescOnce.Do(func() {
		file_preview_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_preview_proto_rawDesc), len(file_preview_proto_rawDesc)))
	})
	return file_preview_proto_rawDescData
}

var file_preview_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_preview_proto_goTypes = []any{
	(*PreviewRequest)(nil),  // 0: preview.PreviewRequest
	(*PreviewResponse)(nil), // 1: preview.PreviewResponse
}
var file_preview_proto_depIdxs = []int32{
	0, // 0: preview.PreviewService.GetPreview:input_type -> preview.PreviewRequest
	1, // 1: preview.PreviewService.GetPreview:output_type -> preview.PreviewResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_preview_proto_init() }
func file_preview_proto_init() {
	if File_preview_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_preview_proto_rawDesc), len(file_preview_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_preview_proto_goTypes,
		DependencyIndexes: file_preview_proto_depIdxs,
		MessageInfos:      file_preview_proto_msgTypes,
	}.Build()
	File_preview_proto = out.File
	file_preview_proto_goTypes = nil
	file_preview_proto_depIdxs = nil
}
